version: "3.9"
services:
  build:
    image: node:22-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: ["npm", "install", "&&", "npm", "run", "build"]
  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/hectorsaravia.conf
    depends_on:
      - build
